run "main" {
  assert {
    condition = data.js_program.main.content == chomp(
      <<-EOT
      // Code generated by JS.tf vdev (https://registry.terraform.io/providers/koki-develop/js/dev)
      const message="hello world";console.log(message)
      EOT
    )

    error_message = ""
  }
}
