run "main" {
  assert {
    condition = local_file.main.content == chomp(
      <<-EOT
      // Code generated by JS.tf vdev (https://registry.terraform.io/providers/koki-develop/js/dev)
      function main(input){const ab=input.split(" ").map(Number);if(ab[0]*ab[1]%2===0){console.log("Even")}else{console.log("Odd")}}main(require("fs").readFileSync("/dev/stdin","utf8"))
    EOT
    )
    error_message = ""
  }
}
