run "main" {
  assert {
    condition = local_file.main.content == chomp(
      <<-EOT
      // Code generated by JS.tf vdev (https://registry.terraform.io/providers/koki-develop/js/dev)
      function main(input){const lines=input.split("\n");const aa=lines[1].split(" ");let nums=aa.map(Number);let count=0;function isEven(num){return num%2===0}function half(num){return num/2}while(nums.every(isEven)){nums=nums.map(half);count++}console.log(count)}main(require("fs").readFileSync("/dev/stdin","utf8"))
      EOT
    )
    error_message = ""
  }
}
