run "main" {
  assert {
    condition = local_file.main.content == chomp(
      <<-EOT
      // Code generated by JS.tf vdev (https://registry.terraform.io/providers/koki-develop/js/dev)
      function main(input){const ny=input.trim().split(" ");const n=Number(ny[0]);const y=Number(ny[1]);for(let i=0;i<=n;i++){for(let j=0;j<=n-i;j++){const k=n-i-j;if(10000*i+5000*j+1000*k===y){console.log(i,j,k);return}}}console.log(-1,-1,-1)}main(require("fs").readFileSync("/dev/stdin","utf8"))
      EOT
    )
    error_message = ""
  }
}
