run "main" {
  assert {
    condition = local_file.main.content == chomp(
      <<-EOT
      // Code generated by JS.tf vdev (https://registry.terraform.io/providers/koki-develop/js/dev)
      function main(input){const nab=input.split(" ").map(Number);let sum=0;for(let i=0;i<=nab[0];i++){const cmp=i.toString().split("").map(Number).reduce(function(acc,cur){return acc+cur},0);if(nab[1]<=cmp&&cmp<=nab[2]){sum+=i}}console.log(sum)}main(require("fs").readFileSync("/dev/stdin","utf8"))
      EOT
    )
    error_message = ""
  }
}
