run "main" {
  assert {
    condition = local_file.main.content == chomp(
      <<-EOT
    // Code generated by JS.tf vdev (https://registry.terraform.io/providers/koki-develop/js/dev)
    const str="hello";const num=10;const bool=true;const arr=[1,2,3];const obj={"foo":3,"hoge":"fuga"}
    EOT
    )
    error_message = ""
  }
}
