run "main" {
  assert {
    condition = local_file.main.content == chomp(
      <<-EOT
      // Code generated by JS.tf vdev (https://registry.terraform.io/providers/koki-develop/js/dev)
      function main(input){function sortDesc(nums){return nums.sort(function(a,b){return b-a})}const aa=input.split("\n")[1].split(" ");const cards=aa.map(Number);sortDesc(cards);let alice=0;let bob=0;for(let i=0;i<cards["length"];i++){if(i%2===0){alice+=cards[i]}else{bob+=cards[i]}}console.log(alice-bob)}main(require("fs").readFileSync("/dev/stdin","utf8"))
      EOT
    )
    error_message = ""
  }
}
