run "main" {
  assert {
    condition = local_file.main.content == chomp(
      <<-EOT
      // Code generated by JS.tf vdev (https://registry.terraform.io/providers/koki-develop/js/dev)
      function main(input){console.log(input.split("").filter(function(s){return s==="1"})["length"])}main(require("fs").readFileSync("/dev/stdin","utf8"))
    EOT
    )
    error_message = ""
  }
}
