package datasources

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/koki-develop/terraform-provider-js/internal/util"
	"github.com/tdewolff/minify/v2"
	"github.com/tdewolff/minify/v2/js"
)

var (
	_ datasource.DataSource = &dataProgram{}
)

func NewDataProgram(version string) func() datasource.DataSource {
	return func() datasource.DataSource {
		m := minify.New()
		m.AddFunc("js", js.Minify)
		return &dataProgram{ProviderVersion: version, Minifier: m}
	}
}

type dataProgram struct {
	ProviderVersion string
	Minifier        *minify.M
}

func (d *dataProgram) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_program"
}

func (d *dataProgram) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"statements": schema.ListAttribute{
				Description: "Statements that are executed in the program.",
				ElementType: types.StringType,
				Required:    true,
			},

			"content": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type dataProgramModel struct {
	Statements types.List `tfsdk:"statements"`

	Content types.String `tfsdk:"content"`
}

func (d *dataProgram) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	util.HandleRequest(
		ctx,
		&dataProgramModel{},
		&req.Config,
		&resp.State,
		&resp.Diagnostics,
		func(m *dataProgramModel) bool {
			header := fmt.Sprintf("// Code generated by JS.tf v%[1]s (https://registry.terraform.io/providers/koki-develop/js/%[1]s)", d.ProviderVersion)

			s := new(strings.Builder)
			s.WriteString(util.StringifyStatements(m.Statements.Elements()))
			content, err := d.Minifier.String("js", s.String())
			if err != nil {
				resp.Diagnostics.AddError("Failed to minify JavaScript", err.Error())
				return false
			}
			m.Content = types.StringValue(fmt.Sprintf("%s\n%s", header, content))
			return true
		},
	)
}
