run "main" {
  assert {
    condition = local_file.main.content == chomp(
      <<-EOT
      // Code generated by JS.tf vdev (https://registry.terraform.io/providers/koki-develop/js/dev)
      function main(input){const s=input.trim().replaceAll("eraser","").replaceAll("erase","").replaceAll("dreamer","").replaceAll("dream","");if(s===""){console.log("YES")}else{console.log("NO")}}main(require("fs").readFileSync("/dev/stdin","utf8"))
      EOT
    )
    error_message = ""
  }
}
