name: Test

on: push

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go test -v ./...

  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.2
      - name: test
        working-directory: examples
        run: |
          for wd in $(ls -d */); do
            cd $wd
            terraform init
            terraform test
          done
